# Generated by Django 5.2.11 on 2026-03-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='est_active',
            field=models.BooleanField(default=False),
        ),
    ]
