# Generated by Django 5.2.11 on 2026-03-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_alter_location_est_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='decision',
            field=models.CharField(choices=[('EN', 'En attente'), ('AC', 'Acceptée'), ('RF', 'Refusée')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='delai_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='est_terminer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='montant_partiel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='location',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='paiement_partiel_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='paiement_total_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='pourcentage_partiel',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Pourcentage du paiement partiel (par défaut 30%)', max_digits=5),
        ),
    ]
