# Generated by Django 5.2.11 on 2026-03-19 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0004_alter_location_client_alter_location_voiture'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
