# Generated by Django 5.2.11 on 2026-03-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0005_location_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cause_rejet',
            field=models.TextField(blank=True, help_text="Raison du refus si la location est refusée par l'admin", null=True),
        ),
    ]
