# Generated by Django 5.2.11 on 2026-03-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='clientphoto/photo.jpg', upload_to='clientphoto/'),
        ),
    ]
