# Generated by Django 5.2.11 on 2026-03-06 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='marques/')),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField()),
                ('carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Electrique'), ('hybride', 'Hybride')], default='essence', max_length=20)),
                ('boite', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='Voiture.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=20)),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='voitures/')),
                ('kilometrage', models.IntegerField(default=0, help_text='Kilométrage en km')),
                ('location_disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voitures', to='Voiture.modele')),
            ],
        ),
        migrations.CreateModel(
            name='ImageVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='voitures/')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Voiture.voiture')),
            ],
        ),
    ]
